# -*- coding: utf-8 -*-
# all available properties in serverless.yml when provider is aws
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service:
  name: learn-awslambda

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  profile: sanhe
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: sanhe-learn-aws-lambda-with-sls-deploy
  deploymentPrefix: serverless
  role: arn:aws:iam::663351365541:role/learn_awslambda
  versionFunctions: false

package:
  artifact: ./build/lambda/source.zip

functions:
  numpy_ver:
    handler: learn_awslambda.handlers.numpy_ver.handler
    description:
    layers:
      - arn:aws:lambda:us-east-1:663351365541:layer:learn_awslambda:4
  pandas_ver:
    handler: learn_awslambda.handlers.pandas_ver.handler
    description:
    layers:
      - arn:aws:lambda:us-east-1:663351365541:layer:learn_awslambda:4
  sum_all:
    handler: learn_awslambda.handlers.sum_all.handler
    description:
    layers:
      - arn:aws:lambda:us-east-1:663351365541:layer:learn_awslambda:4
